---
title: "CR_B2"
author: "Finn & Victoria"
date: "2024-05-16"
output: html_document
---

```{r, warning= FALSE, message=FALSE}
library(dplyr)
library(tidyr)

install.packages("openxlsx")
library(openxlsx)
```

#Import data

```{r}
survey_data <- read.xlsx("data/CR24 Spring class survey raw data.xlsx") #load from data file
colnames(survey_data) <- make.names(colnames(survey_data), unique = TRUE)
survey_data <- survey_data[, -(1:7)] #remove unnecessary columns from 1:7

#change age to numeric
survey_data$`What.is.your.age.` <- as.numeric(survey_data$`What.is.your.age.`)

#remove the data with 55000 make per hour
survey_data <- survey_data %>%
  filter(`How.much.money.do.you.make.per.hour.of.work.at.your.job.` != 55000)

#no missing data, removed the 55000 Outliers
summary(survey_data)
```

```{r}
#calculate gender, 1= Male, 2=Female
gender_distribution <- survey_data %>%
  group_by(What.gender.do.you.identify.with.) %>%
  summarise(Count = n())

print(gender_distribution)
```


```{r}
## split the data into groups
colnames(survey_data)[ncol(survey_data)] <- "order"

#remove all the NA columns from each group
remove_na_columns <- function(df) {
  df %>%
    select_if(~!all(is.na(.)))
}


MoneyasTimeLongTerm <- survey_data %>%
  filter(order %in% c("MoneyasTimeLongTerm")) %>% 
  remove_na_columns()

MoneyasTimeWorkedImmediate <- survey_data %>%
  filter(order %in% c("MoneyasTimeWorkedImmediate"))%>% 
  remove_na_columns()

MoneyImmediate <- survey_data %>%
  filter(order %in% c("MoneyImmediate"))%>% 
  remove_na_columns()

Moneylongterm <- survey_data %>%
  filter(order %in% c("Moneylongterm"))%>% 
  remove_na_columns()

```

